---
title: "analisis"
author: "Mateusz Kapiszewski, Jakub Sztyma"
date: "November 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Used libraries
```{r libraries}
library(corrplot)
library(DAAG)
```

## Set seed to make experiment results recurrent
```{r set seed}
set.seed(5)
```

## Read data from file
```{r read data}
filename <- "sledzie.csv"
df <- read.csv(filename, na.strings=c("?"), nrows = 1000)
df <- df[, names(df) != 'X'] # Remove column X
print("Is data.frame instance?")
print(is.data.frame(df))
```

## Parse data
```{r parse data}
full_rows <- complete.cases(df)
df <- df[full_rows,]
print(df)
```

## Data set summary
```{r summary}

print("Size of cleared data:")
print(nrow(df))
print(summary(df))
```

## Show attribute distributions
```{r attributes distribution}
for(name in names(df)){
  d <- density(df[, name])
  plot(d, main="Density")
}
```

## Show correlation matrix
```{r correlation matrix}
corr_matrix <- cor(df)
corrplot(corr_matrix, method="pie", col=c("black", "white"), bg="lightblue")
```

## Herring length in time
```{r length in time}

```

## Regression model
```{r regression}
# sst has the biggest correlation with length
# cfin2 has big correlation with length and relatively small with sst
# nao has correlation with length but does not have big correlation with sst or cfin2
# There is no need in adding more attributes to regression as the rest of attributes are very much correlated
formula <- length ~ sst + cfin2 + nao
linearMod <- lm(formula, data=df)  # build linear regression model on full data
summary(linearMod)

cvResults <- suppressWarnings(CVlm(df, form.lm=formula, m=5, dots=FALSE, seed=29, legend.pos="topleft",  printit=FALSE, main="Small symbols are predicted values while bigger ones are actuals."));  # performs the CV
attr(cvResults, 'ms')

```
